fix: don't split paths on `^` characters
ipfs/js-ipfs-unixfs pull request #192
Opened 2022-01-31 15:37 UTC by yusefnapora

This removes the extra `^` char from [this regex](https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-importer/src/utils/to-path-components.js#L5) that was causing us to treat the `^` as a path separator.

Closes #177, and will fix https://github.com/web3-storage/web3.storage/issues/375 when pulled into the web3.storage client.

2022-02-04 15:17 UTC, alanshaw requested changes
Can it be tested?

I used http://www.regexplained.co.uk/ to make sense of this...

2022-02-18 15:22 UTC, lidel commented
This needs tests :)

2022-03-04 15:32 UTC, lidel commented
Still needs tests :^)

2022-03-18 14:05 UTC, BigLep commented
@yusefnapora : are you going to add tests so that this can land?

2022-03-29 16:26 UTC, yusefnapora commented
hey everyone, sorry for sleeping on this! will add tests today

2022-04-11 14:19 UTC, vasco-santos approved these changes
LGTM

2022-04-12 16:32 UTC, merged