feat: add config option to control fanout size
ipfs/js-ipfs-unixfs pull request #356
Opened 2023-08-24 17:37 UTC by achingbrain

Adds a `shardFanoutBytes` option to the importer to allow configuring the number of bytes used for the HAMT prefix, also a test.

2023-08-24 18:24 UTC, SgtPooki requested changes

2023-08-24 18:24 UTC, SgtPooki commented on packages/ipfs-unixfs-importer/src/index.ts
> +   * The maximum number of bytes used as a HAMT prefix for shard entries. Default: 256
default seems to be 8 bits (1 byte) above? change this comment, or actual default?

2023-08-24 18:24 UTC, SgtPooki commented on packages/ipfs-unixfs-importer/src/index.ts
> +  const shardFanoutBytes = options.shardFanoutBytes ?? 8
is 8 bytes the default, or 256?

2023-08-25 06:09 UTC, rvagg commented
Made my suggested changes in #357 - going with "bits" - the nice thing about using bits is that you don't have to worry about divisibility. You can't really do a fanout that's not a power of 2, so start low and power up from the bit count.

2023-08-25 06:17 UTC, alanshaw approved these changes

2023-08-25 06:19 UTC, merged

2023-08-25 10:26 UTC, achingbrain commented
It was `bytes` because the shard split threshold option next to it was `bytes` so it was a (flawed) attempt to keep the units consistent, but quite right `bits` is more correct.  Thanks all.